spring:
  application:
    name: header-One
  activemq:
    broker-url: tcp://localhost:61616
  sleuth:
    baggage:
      remote-fields: businessId
      correlation-fields: businessId
    messaging:
      enabled: true



logging:
  level:
    org.apache.activemq.broker: INFO



